### ISSUE TITLE
ical hitting "invalid cert" issue

### ISSUE THREAD

**Issue by caseysoftware** [ThatConference/thatconference.com#214]
**Describe the bug**

As named

**To Reproduce**

1. Visit https://thatconference.com/support/my-favorites-icalendar
2. Copy the link
3. Try to load the link, get an SSL cert error from Cloudflare
4. Everyone dies

**Expected behavior**
I should see my ical feed

**Screenshots**
n/a

**Desktop (please complete the following information):**

same via browsing and curl

**Smartphone (please complete the following information):**

didn't try

**Additional context**

n/a

**Comment by brettski** [comment]
This has been fixed.
