### ISSUE TITLE
Session details && trailing slash issue

### ISSUE THREAD

**Issue by brettski** [ThatConference/thatconference.com#42]
Going to session details at `activities/<slug>`, if there is a trailing slash in the URL it causes a 500 error. 

When clicking on an activity card from the schedule, the site directs the use to `/activities/<slug>` without a trailing slash and the page loads. If you go directly to the url, e.g. https://feature.thatconference.com/activities/qYC0VRCTq22vNOf8p0pq, the site will add a trailing slash to the url and throw a 500 error.

When the request works, when you go to an activity url directly, https://feature.thatconference.com/activities/qYC0VRCTq22vNOf8p0pq, the site will add the trailing slash, then remove it. Based on site settings `trailingSlash = 'always'`

The functionality isn't consistent where sometimes the page will load an other times it doesn't, resulting in a 500.
https://feature.thatconference.com/activites/qYC0VRCTq22vNOf8p0pq/
vs.
https://feature.thatconference.com/activites/qYC0VRCTq22vNOf8p0pq

When successful the route seems to remove the trailing slash and I couldn't find how that is being done in the site. There is something inconsistent going on here. 
I was unable to get this to fail locally.

**Comment by csell5** [comment]
There appears to be still an issue related to a new login.

**Comment by csell5** [comment]
can't seem to reproduce anylong
