### ISSUE TITLE
Home Page Buttons off on iPad Landscape mode

### ISSUE THREAD

**Issue by zaudtke** [ThatConference/thatconference.com#75]
**Describe the bug**
I noticed this on my 8th Gen iPad in Landscape mode using Safari.
The buttons for THAT Conference Wisconsin and THAT Conference Texas display incorrectly.  The text wraps, but the button doesn't accommodate it.

**To Reproduce**
If it works on larger iPads, it can be reproduced in browser developer tools by setting it to iPad Mini and making sure in landscape mode.

**Screenshots**
![Screenshot 2023-09-21 125118](https://github.com/ThatConference/thatconference.com/assets/1631560/31b8de7c-98db-4e13-a8d6-d02a2f94d805)

**Comment by csell5** [comment]
Oh that's our new UX design. We're not sure where we're starting or ending.

**Comment by zaudtke** [comment]
Idea:  THAT Texas and THAT Wisconsin.  Drop `Conference` ?

**Comment by csell5** [comment]
@all-contributors please add @zaudtke for bug
